# base image
FROM node:20-alpine

WORKDIR /usr/src/app

# install dependencies
COPY package*.json ./
RUN npm install

# copy everything
COPY . .

# expose port
EXPOSE 3000

# default command
CMD ["npm", "run", "start:dev"]
